trigger:
  batch: true
  branches:
    include:
      - master

pool: Default

variables:
  - name: buildConfiguration
    value: 'Release'

resources:
  repositories:
    - repository: templates
      type: git
      name: DevShared/Templates

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - template: steps/dotnet-test-and-publish-results.yml@templates
    parameters:
      buildConfiguration: '$(BuildConfiguration)'
