trigger:
  batch: true
  branches:
    include:
      - master

pool: Default

variables:
  - group: Nuget

steps:
  - pwsh: |
      dotnet build "$(Build.SourcesDirectory)/Kros.AspNetCore.sln" --configuration Release
    displayName: Build

  - pwsh: |
      dotnet test "$(Build.SourcesDirectory)/Kros.AspNetCore.sln" --configuration Release --logger trx --results-directory "$(Common.TestResultsDirectory)"
    displayName: Test

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '*.trx'
      searchFolder: $(Common.TestResultsDirectory)

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - task: CopyFiles@2
      displayName: Copy packages to staging folder
      inputs:
        contents: |
          **/*.nupkg
          **/*.snupkg
        targetFolder: $(Build.ArtifactStagingDirectory)
        flattenFolders: true

    - pwsh: |
        $nupkgFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Filter "*.nupkg"
        Write-Host "Found $($nupkgFiles.Count) .nupkg file(s) to push"
        $nupkgFiles | ForEach-Object {
          Write-Host "Pushing $($_.FullName)"
          & dotnet nuget push "$($_.FullName)" --source https://api.nuget.org/v3/index.json --api-key $(nugetOrgApiKey) --skip-duplicate
          Write-Host
        }
      displayName: Push packages to server
